# Generated by Django 6.0.6 on 2026-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nama Produk")),
                ("price", models.IntegerField(verbose_name="Harga")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="Stok Gudang"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="produk_sterno/", verbose_name="Foto Produk"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
