# Generated by Django 6.0.6 on 2026-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=250, unique=True)),
                (
                    "kontak",
                    models.CharField(
                        blank=True, default="-", max_length=250, unique=True
                    ),
                ),
                (
                    "telepon",
                    models.CharField(
                        blank=True, default="-", max_length=50, unique=True
                    ),
                ),
                ("alamat", models.TextField(blank=True, default="-", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
