# Generated by Django 6.0.6 on 2026-06-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=250, unique=True)),
                ("kontak", models.CharField(blank=True, default="-", max_length=250)),
                ("telepon", models.CharField(blank=True, default="-", max_length=50)),
                ("alamat", models.TextField(blank=True, default="-")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PosTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=50, unique=True)),
                ("pelanggan", models.CharField(max_length=150)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("tanggal", models.DateField()),
                (
                    "metode_bayar",
                    models.CharField(
                        choices=[("TUNAI", "Tunai"), ("TEMPO/KREDIT", "Tempo/Kredit")],
                        default="TUNAI",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Lunas", "Lunas"), ("Tempo", "Tempo")],
                        default="Lunas",
                        max_length=20,
                    ),
                ),
                ("ongkir", models.IntegerField(default=0)),
                ("grand_total", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=50)),
                ("pelanggan", models.CharField(max_length=255)),
                ("alamat_pengiriman", models.TextField(blank=True, default="Jakarta")),
                ("tanggal", models.DateField()),
                ("ongkir", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "proforma_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=30)),
                ("nama_produk", models.CharField(max_length=200)),
                ("qty", models.IntegerField()),
                ("harga", models.IntegerField()),
                ("total", models.BigIntegerField()),
                (
                    "transaksi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.postransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("nama_produk", models.CharField(max_length=255)),
                ("qty", models.IntegerField()),
                ("harga", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.proformainvoice",
                    ),
                ),
            ],
            options={
                "db_table": "proforma_invoice_item",
            },
        ),
    ]
