# Generated by Django 6.0.6 on 2026-06-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=50, unique=True)),
                ("pelanggan", models.CharField(max_length=255)),
                ("alamat_pengiriman", models.TextField(blank=True, default="Jakarta")),
                ("tanggal", models.DateField()),
                ("ongkir", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "proforma_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("nama_produk", models.CharField(max_length=255)),
                ("qty", models.IntegerField()),
                ("harga", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.proformainvoice",
                    ),
                ),
            ],
            options={
                "db_table": "proforma_invoice_item",
            },
        ),
    ]
