# Generated by Django 6.0.6 on 2026-06-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_proformainvoice_proformainvoiceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=50, unique=True)),
                ("pelanggan", models.CharField(max_length=150)),
                ("tanggal", models.DateField()),
                (
                    "metode_bayar",
                    models.CharField(
                        choices=[("TUNAI", "Tunai"), ("TEMPO/KREDIT", "Tempo/Kredit")],
                        default="TUNAI",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Lunas", "Lunas"), ("Tempo", "Tempo")],
                        default="Lunas",
                        max_length=20,
                    ),
                ),
                ("ongkir", models.IntegerField(default=0)),
                ("grand_total", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="nomor_invoice",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="PosTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=30)),
                ("nama_produk", models.CharField(max_length=200)),
                ("qty", models.IntegerField()),
                ("harga", models.IntegerField()),
                ("total", models.BigIntegerField()),
                (
                    "transaksi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.postransaction",
                    ),
                ),
            ],
        ),
    ]
