# Generated by Django 6.0.6 on 2026-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_postransaction_alter_proformainvoice_nomor_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postransaction",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
    ]
