# Generated by Django 6.0.6 on 2026-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_postransaction_alamat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="alamat",
            field=models.TextField(blank=True, default="-"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="kontak",
            field=models.CharField(blank=True, default="-", max_length=250),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telepon",
            field=models.CharField(blank=True, default="-", max_length=50),
        ),
    ]
