# Generated by Django 6.0.6 on 2026-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("nama", models.CharField(max_length=200)),
                ("min_stock", models.IntegerField(default=0)),
                ("satuan", models.CharField(default="Pcs", max_length=50, unique=True)),
            ],
        ),
    ]
