# Generated by Django 6.0.6 on 2026-06-16 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("nama", models.CharField(max_length=200)),
                ("min_stok", models.IntegerField(default=0)),
                ("satuan", models.CharField(default="Pcs", max_length=50)),
                ("stok_aktual", models.IntegerField(default=0)),
                ("hpp", models.IntegerField(default=0)),
                ("harga_jual", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_po", models.CharField(max_length=100, unique=True)),
                ("supplier", models.CharField(max_length=255)),
                ("tanggal", models.DateField(default=django.utils.timezone.now)),
                ("grand_total", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255, unique=True)),
                ("kontak", models.CharField(blank=True, default="-", max_length=255)),
                (
                    "telepon",
                    models.CharField(blank=True, default="-", max_length=50, null=True),
                ),
                (
                    "rekening",
                    models.CharField(
                        blank=True, default="-", max_length=255, null=True
                    ),
                ),
                ("alamat", models.TextField(blank=True, default="-", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("nama_produk", models.CharField(max_length=255)),
                ("qty", models.IntegerField(default=1)),
                ("harga_beli", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
