# Generated by Django 6.0.6 on 2026-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stok_aktual",
            field=models.IntegerField(default=0),
        ),
    ]
