# Generated by Django 6.0.6 on 2026-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.IntegerField()),
                ("bulan", models.IntegerField()),
                ("nilai_counter", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "inventory_po_counter",
                "unique_together": {("tahun", "bulan")},
            },
        ),
    ]
