# Generated by Django 6.0.6 on 2026-06-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_stok_aktual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="min_stock",
            new_name="min_stok",
        ),
    ]
