# Generated by Django 6.0.6 on 2026-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_rename_min_stock_product_min_stok"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="harga_jual",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="hpp",
            field=models.IntegerField(default=0),
        ),
    ]
