# Generated by Django 6.0.6 on 2026-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_harga_jual_product_hpp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255, unique=True)),
                (
                    "kontak",
                    models.CharField(
                        blank=True, default="-", max_length=255, unique=True
                    ),
                ),
                (
                    "telepon",
                    models.CharField(blank=True, default="-", max_length=50, null=True),
                ),
                (
                    "rekening",
                    models.CharField(
                        blank=True, default="-", max_length=255, null=True
                    ),
                ),
                ("alamat", models.TextField(blank=True, default="-", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
