# Generated by Django 6.0.6 on 2026-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_purchaseorder_purchaseorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="satuan",
            field=models.CharField(default="Pcs", max_length=50),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="kontak",
            field=models.CharField(blank=True, default="-", max_length=255),
        ),
    ]
