# Generated by Django 6.0.6 on 2026-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Piutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=100, unique=True)),
                ("pelanggan", models.CharField(max_length=255)),
                ("tanggal_transaksi", models.DateField()),
                ("jatuh_tempo", models.DateField()),
                ("total_tagihan", models.IntegerField()),
                ("sisa_piutang", models.IntegerField()),
                (
                    "status_piutang",
                    models.CharField(default="Belum Lunas", max_length=50),
                ),
            ],
        ),
    ]
