# Generated by Django 6.0.6 on 2026-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("kategori", models.CharField(max_length=100)),
                (
                    "metode",
                    models.CharField(
                        choices=[
                            ("Tunai / Kas Kecil", "Tunai / Kas Kecil"),
                            ("Transfer Bank", "Transfer Bank"),
                        ],
                        default="Tunai / Kas Kecil",
                        max_length=50,
                    ),
                ),
                ("nominal", models.BigIntegerField()),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_po", models.CharField(max_length=100, unique=True)),
                ("supplier", models.CharField(max_length=255)),
                ("tanggal_po", models.DateField()),
                ("deskripsi_barang", models.TextField(blank=True, null=True)),
                ("total_tagihan", models.BigIntegerField()),
                ("sisa_hutang", models.BigIntegerField()),
                (
                    "status_hutang",
                    models.CharField(
                        choices=[
                            ("Belum Lunas", "Belum Lunas"),
                            ("On Process", "On Process"),
                            ("Lunas", "Lunas"),
                        ],
                        default="Belum Lunas",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_hutang",
                "ordering": ["tanggal_po"],
            },
        ),
        migrations.CreateModel(
            name="Piutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_invoice", models.CharField(max_length=100, unique=True)),
                ("pelanggan", models.CharField(max_length=255)),
                ("tanggal_transaksi", models.DateField()),
                ("jatuh_tempo", models.DateField()),
                ("total_tagihan", models.BigIntegerField()),
                ("sisa_piutang", models.BigIntegerField()),
                (
                    "status_piutang",
                    models.CharField(
                        choices=[
                            ("Belum Lunas", "Belum Lunas"),
                            ("Cicilan", "Cicilan / Dibayar Sebagian"),
                            ("Lunas", "Lunas"),
                        ],
                        default="Belum Lunas",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_piutang",
                "ordering": ["jatuh_tempo"],
            },
        ),
    ]
