# Generated by Django 6.0.6 on 2026-06-14 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piutang",
            options={"ordering": ["jatuh_tempo"]},
        ),
        migrations.AddField(
            model_name="piutang",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="piutang",
            name="sisa_piutang",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="piutang",
            name="status_piutang",
            field=models.CharField(
                choices=[
                    ("Belum Lunas", "Belum Lunas"),
                    ("Cicilan", "Cicilan / Dibayar Sebagian"),
                    ("Lunas", "Lunas"),
                ],
                default="Belum Lunas",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="piutang",
            name="total_tagihan",
            field=models.BigIntegerField(),
        ),
        migrations.AlterModelTable(
            name="piutang",
            table="finance_piutang",
        ),
    ]
