# Generated by Django 6.0.6 on 2026-06-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Nama Pembeli"),
                ),
                (
                    "customer_whatsapp",
                    models.CharField(max_length=20, verbose_name="No. WhatsApp"),
                ),
                (
                    "shipping_region",
                    models.CharField(max_length=100, verbose_name="Wilayah Pengiriman"),
                ),
                (
                    "courier_service",
                    models.CharField(max_length=50, verbose_name="Layanan Kurir"),
                ),
                (
                    "status",
                    models.CharField(
                        default="Pending/WhatsApp", max_length=30, verbose_name="Status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Waktu Masuk"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Jumlah (Qty)")),
                (
                    "price_at_purchase",
                    models.IntegerField(verbose_name="Harga Saat Transaksi"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checkout.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                        verbose_name="Produk",
                    ),
                ),
            ],
        ),
    ]
